---

- name: Set up all the things
  hosts: localhost
  tasks:
  - name: Execute Homebrew tasks
    import_tasks: tasks/homebrew.yml
    tags: ['mac', 'homebrew', 'brew']
    when: ansible_distribution == "MacOSX"

  - name: Execute App Store tasks
    import_tasks: tasks/app_store.yml
    tags: ['mac', 'app_store']
    when: ansible_distribution == "MacOSX"

  - name: Execute iTerm tasks
    import_tasks: tasks/iterm.yml
    tags: ['mac', 'iterm']
    when: ansible_distribution == "MacOSX"

  - name: Execute dotfiles tasks
    import_tasks: tasks/dotfiles.yml
    tags: ['dotfiles']

  - name: Execute asdf tasks
    import_tasks: tasks/asdf.yml
    tags: ['asdf']

  - name: Execute Oh My Zsh tasks
    import_tasks: tasks/oh_my_zsh.yml
    tags: ['zsh']

  - name: Execute scm_breeze tasks
    import_tasks: tasks/scm_breeze.yml
    tags: ['scm']

  - name: Execute Docker tasks
    import_tasks: tasks/docker.yml
    tags: ['docker']
