---

- name: Set up all the things

  hosts: localhost

  tasks:
    - name: Execute Debian tasks
      import_tasks: tasks/debian.yml
      tags: ['debian', 'ubuntu']
      when: ansible_facts['os_family'] == "Debian"

    - name: Execute macOS tasks
      import_tasks: tasks/macos.yml
      tags: ['macos', 'mac']
      when: ansible_distribution == "MacOSX"

    - name: Execute dotfiles tasks
      import_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']

    - name: Execute Zsh tasks
      import_tasks: tasks/zsh.yml
      tags: ['zsh']

    - name: Execute Neovim tasks
      import_tasks: tasks/neovim.yml
      tags: ['neovim', 'nvim']
      when: ansible_distribution != "MacOSX"

    - name: Execute mise tasks
      import_tasks: tasks/mise.yml
      tags: ['mise']

    - name: Execute scm_breeze tasks
      import_tasks: tasks/scm_breeze.yml
      tags: ['scm']

    # - name: Execute Docker tasks
    #   import_tasks: tasks/docker.yml
    #   tags: ['docker']
