---

- name: Set up all the things

  hosts: localhost

  vars_files:
    - vars/asdf.yml
    - vars/homebrew.yml
    - vars/mas.yml

  tasks:
    - name: Execute Mac OS tasks
      import_tasks: tasks/mac.yml
      tags: ['macos', 'mac']
      when: ansible_distribution == "MacOSX"

    - name: Execute dotfiles tasks
      import_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']

    - name: Execute asdf tasks
      import_tasks: tasks/asdf.yml
      tags: ['asdf']

    - name: Execute Oh My Zsh tasks
      import_tasks: tasks/oh_my_zsh.yml
      tags: ['zsh']

    - name: Execute scm_breeze tasks
      import_tasks: tasks/scm_breeze.yml
      tags: ['scm']

    - name: Execute Docker tasks
      import_tasks: tasks/docker.yml
      tags: ['docker']
