---

- name: Set up all the things

  hosts: localhost

  vars_files:
    - vars/apt.yml

  tasks:
    - name: Execute Debian tasks
      import_tasks: tasks/debian.yml
      tags: ['debian', 'ubuntu']
      when: ansible_facts['os_family'] == "Debian"

    - name: Execute dotfiles tasks
      import_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']

    - name: Execute Zsh tasks
      import_tasks: tasks/zsh.yml
      tags: ['zsh']

    - name: Execute asdf tasks
      import_tasks: tasks/asdf.yml
      tags: ['asdf']

    - name: Execute scm_breeze tasks
      import_tasks: tasks/scm_breeze.yml
      tags: ['scm']

    # - name: Execute Docker tasks
    #   import_tasks: tasks/docker.yml
    #   tags: ['docker']
