---

- name: Set up all the things
  hosts: localhost
  tasks:
  - name: Execute Homebrew tasks
    include_tasks:
      file: tasks/homebrew.yml
      apply:
        tags: ['mac', 'homebrew', 'brew']
    tags: ['mac', 'homebrew', 'brew']
    when: ansible_distribution == "MacOSX"

  - name: Execute App Store tasks
    include_tasks:
      file: tasks/app_store.yml
      apply:
        tags: ['mac', 'app_store']
    tags: ['mac', 'app_store']
    when: ansible_distribution == "MacOSX"

  - name: Execute iTerm tasks
    include_tasks:
      file: tasks/iterm.yml
      apply:
        tags: ['mac', 'iterm']
    tags: ['mac', 'iterm']
    when: ansible_distribution == "MacOSX"

  - name: Execute dotfiles tasks
    include_tasks:
      file: tasks/dotfiles.yml
      apply:
        tags: ['dotfiles']
    tags: ['dotfiles']

  - name: Execute asdf tasks
    include_tasks:
      file: tasks/asdf.yml
      apply:
        tags: ['asdf']
    tags: ['asdf']

  - name: Execute Oh My Zsh tasks
    include_tasks:
      file: tasks/oh_my_zsh.yml
      apply:
        tags: ['zsh']
    tags: ['zsh']

  - name: Execute scm_breeze tasks
    include_tasks:
      file: tasks/scm_breeze.yml
      apply:
        tags: ['scm']
    tags: ['scm']

  - name: Execute Docker tasks
    include_tasks:
      file: tasks/docker.yml
      apply:
        tags: ['docker']
    tags: ['docker']
