---

- name: Include App Store variables
  ansible.builtin.include_vars: vars/app_store.yml

- name: Open App Store
  ansible.builtin.shell: open "/System/Applications/App Store.app"

- name: Install App store apps
  ansible.builtin.shell: mas install "{{ item }}"
  loop: "{{ mas.apps }}"
