---

- name: Open App Store
  ansible.builtin.shell: open "/System/Applications/App Store.app"

- name: Install App store apps
  ansible.builtin.shell: mas install "{{ item }}"
  loop: "{{ mas.apps }}"
