---

- name: Update cache and install apt packages
  ansible.builtin.apt:
    name: "{{ apt.packages }}"
    update_cache: yes

- name: Install delta (git-delta)
  ansible.builtin.apt:
    deb: https://github.com/dandavison/delta/releases/download/0.16.5/git-delta_0.16.5_amd64.deb

- name: Update all packages to latest
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Clean and remove dependencies
  ansible.builtin.apt:
    autoclean: yes
    autoremove: yes
