---

- name: Include apt variables
  ansible.builtin.include_vars: vars/apt.yml

- name: Update cache and install apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ apt.packages }}"
    update_cache: yes

- name: Set delta (git-delta) build
  ansible.builtin.set_fact:
    delta_build: "git-delta_{{ delta.version }}_{{ delta.arch[ansible_architecture] | default(ansible_architecture) }}"

- name: Install delta (git-delta)
  become: true
  ansible.builtin.apt:
    deb: "https://github.com/dandavison/delta/releases/download/{{ delta.version }}/{{ delta_build }}.deb"

- name: Update all packages to latest
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Clean and remove dependencies
  become: true
  ansible.builtin.apt:
    autoclean: yes
    autoremove: yes
