---

- name: Install asdf
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "$HOME/.asdf"

- name: Install Node.js
  ansible.builtin.shell: |
    . "$HOME/.asdf/asdf.sh"
    asdf plugin add nodejs
    asdf install nodejs latest
    asdf global nodejs latest

- name: Install Python
  ansible.builtin.shell: |
    . "$HOME/.asdf/asdf.sh"
    asdf plugin add python
    asdf install python latest
    asdf global python latest

- name: Install Ruby
  ansible.builtin.shell: |
    . "$HOME/.asdf/asdf.sh"
    asdf plugin add ruby
    asdf install ruby latest
    asdf global ruby latest
