---

- name: Find dotfile packages to stow
  ansible.builtin.find:
    paths: files/dotfiles
    file_type: directory
  register: stow_packages

- name: Stow dotfiles
  ansible.builtin.shell:
    cmd: stow --adopt "{{ item.path | basename }}" --target="$HOME"
    chdir: files/dotfiles
  loop: "{{ stow_packages.files }}"

- name: Revert any adopted dotfiles
  ansible.builtin.git:
    repo: https://git.bhei.com/edoan/devcontainer-bootstrap.git
    dest: "{{ playbook_dir }}"
    force: true

- name: Restow dotfiles
  ansible.builtin.shell:
    cmd: stow --restow "{{ item.path | basename }}" --target="$HOME"
    chdir: files/dotfiles
  loop: "{{ stow_packages.files }}"
