---

- name: Find packages to stow
  ansible.builtin.find:
    paths: files/dotfiles
    file_type: directory
  register: stow_packages

- name: Stow packages
  ansible.builtin.shell:
    cmd: stow "{{ item.path | basename }}" --target="$HOME"
    chdir: files/dotfiles
  loop: "{{ stow_packages.files }}"
