---

- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_installed_check

- name: Install Homebrew
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: homebrew_installed_check.stat.exists == False

- name: Load Homebrew variables
  ansible.builtin.include_vars: vars/homebrew.yml

- name: Install Homebrew taps
  community.general.homebrew_tap:
    name: "{{ homebrew.taps }}"

- name: Install Homebrew formulae
  community.general.homebrew:
    name: "{{ homebrew.formulae }}"

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ homebrew.casks }}"
    accept_external_apps: yes
