---

- name: Load Homebrew variables
  ansible.builtin.include_vars: vars/homebrew.yml

- name: Get Homebrew install path
  ansible.builtin.shell: brew --prefix
  register: brew_prefix

- name: Install Homebrew taps
  community.general.homebrew_tap:
    name: "{{ homebrew.taps }}"

- name: Install Homebrew formulae
  community.general.homebrew:
    name: "{{ homebrew.formulae }}"

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ homebrew.casks }}"
    accept_external_apps: yes
