---

- name: Stow dynamic profiles
  ansible.builtin.shell:
    cmd: stow iterm --target="$HOME/Library/Application Support/iTerm2"
    chdir: files

- name: Get GUID of main dynamic profile
  ansible.builtin.shell:
    cmd: jq -jr '.Profiles[0].Guid' Main.json
    chdir: files/iterm/DynamicProfiles
  register: iterm_profile_guid

- name: Set main dynamic profile as default profile
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: Default Bookmark Guid
    type: string
    value: "{{ iterm_profile_guid.stdout }}"
    state: present
