---

- name: Include macOS variables
  ansible.builtin.include_vars: "vars/{{ item }}.yml"
  with_items:
    - homebrew
    - mas

- name: Execute Homebrew tasks
  import_tasks: homebrew.yml
  tags: ['homebrew', 'brew']

- name: Execute App Store tasks
  import_tasks: app_store.yml
  tags: ['app_store']
