---

- name: Check if Oh My Zsh is installed
  ansible.builtin.stat:
    path: "$HOME/.oh-my-zsh"
  register: oh_my_zsh_installed_check

- name: Install Oh My Zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: oh_my_zsh_installed_check.stat.exists == False

- name: Check for previous .zshrc
  ansible.builtin.stat:
    path: "$HOME/.zshrc.pre-oh-my-zsh"
  register: previous_zshrc_check

- name: Restore previous .zshrc
  ansible.builtin.shell: mv "{{ previous_zshrc_check.stat.path }}" "$HOME/.zshrc"
  when: previous_zshrc_check.stat.exists == True

- name: Install autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Install Powerlevel10k theme
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "$HOME/.oh-my-zsh/custom/themes/powerlevel10k"
