---

- name: Check if Oh My Zsh is installed
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh_dir

- name: Install Oh My Zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  when: oh_my_zsh_dir.stat.exists == False

- name: Check for previous .zshrc
  ansible.builtin.stat:
    path: ~/.zshrc.pre-oh-my-zsh
  register: previous_zshrc

- name: Restore previous .zshrc
  ansible.builtin.shell: "mv {{ previous_zshrc.stat.path }} ~/.zshrc"
  when: previous_zshrc.stat.exists == True

- name: Install autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ oh_my_zsh_dir.stat.path }}/custom/plugins/zsh-autosuggestions"

- name: Install syntax highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ oh_my_zsh_dir.stat.path }}/custom/plugins/zsh-syntax-highlighting"

- name: Install Powerlevel10k theme
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ oh_my_zsh_dir.stat.path }}/custom/themes/powerlevel10k"
